name:                hs-procr
version:             0.1.0.0
github:              githubuser/hs-procr
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hs-procr#readme>

dependencies:
- base >= 4.7 && < 5
- turtle
- doctest
- regex-base
- regex-tdfa
- zeromq4-haskell
- tasty-hunit
- text
- split
- directory
- filemanip
- foldl
- extra
- mtl
- htaglib

library:
  source-dirs: src

executables:
  hs-procr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-procr

tests:
  hs-procr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-procr
